"""empty message

Revision ID: 00d2fe84db04
Revises: 0c64dc9779f9
Create Date: 2024-12-10 14:28:46.711807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d2fe84db04'
down_revision = '0c64dc9779f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('VMS', sa.String(length=50), nullable=False, comment='机器 VMS 编号'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxies', schema=None) as batch_op:
        batch_op.drop_column('VMS')

    # ### end Alembic commands ###
