"""empty message

Revision ID: 034c8f145f17
Revises: 840702f3fdcd
Create Date: 2025-02-19 10:15:58.480834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034c8f145f17'
down_revision = '840702f3fdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
