"""empty message

Revision ID: 0c64dc9779f9
Revises: 
Create Date: 2024-12-10 14:15:31.600105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c64dc9779f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('internal_ip', sa.String(length=50), nullable=False, comment='内网 IP 地址'),
    sa.Column('external_ip', sa.String(length=50), nullable=False, comment='公网 IP 地址'),
    sa.Column('group_name', sa.String(length=100), nullable=True, comment='分组名称'),
    sa.Column('datacenter', sa.String(length=100), nullable=True, comment='机房位置'),
    sa.Column('company', sa.String(length=100), nullable=True, comment='所属公司'),
    sa.Column('isp_line', sa.String(length=100), nullable=True, comment='ISP 线路信息'),
    sa.Column('specific_line', sa.String(length=100), nullable=True, comment='具体线路信息'),
    sa.Column('frpc_nickname', sa.String(length=100), nullable=True, comment='FRPC 昵称'),
    sa.Column('frpc_description', sa.Text(), nullable=True, comment='FRPC 说明'),
    sa.Column('frps_ports', sa.String(length=50), nullable=True, comment='FRPS 占用或预留端口'),
    sa.Column('supplier', sa.String(length=100), nullable=True, comment='供应商名称'),
    sa.Column('supplier_delivery', sa.Text(), nullable=True, comment='供应商交付内容'),
    sa.Column('access_method', sa.String(length=50), nullable=True, comment='接入方式（如 Squid、FRP）'),
    sa.Column('user', sa.String(length=100), nullable=True, comment='使用方'),
    sa.Column('gost_address', sa.String(length=255), nullable=True, comment='Gost 地址'),
    sa.Column('actual_count', sa.Integer(), nullable=True, comment='实际数量'),
    sa.Column('health_check', sa.String(length=50), nullable=True, comment='健康检测方式'),
    sa.Column('remark_1', sa.Text(), nullable=True, comment='备注 1'),
    sa.Column('remark_2', sa.Text(), nullable=True, comment='备注 2'),
    sa.Column('remark_3', sa.Text(), nullable=True, comment='备注 3'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxies')
    # ### end Alembic commands ###
