"""empty message

Revision ID: 1e98da268fe4
Revises: 9840d06b9339
Create Date: 2024-12-10 15:19:52.748121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e98da268fe4'
down_revision = '9840d06b9339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxies', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', mysql.VARCHAR(length=100), nullable=True, comment='所属公司'))

    # ### end Alembic commands ###
