"""empty message

Revision ID: 5d00ab29f193
Revises: a0d31c19f8fe
Create Date: 2024-12-16 14:52:00.251809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d00ab29f193'
down_revision = 'a0d31c19f8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_frpc', schema=None) as batch_op:
        batch_op.alter_column('actual_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='实际数量')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_frpc', schema=None) as batch_op:
        batch_op.alter_column('actual_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='实际数量')

    # ### end Alembic commands ###
