"""empty message

Revision ID: 5e7f46e566ee
Revises: 1e98da268fe4
Create Date: 2024-12-14 17:02:56.976789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e7f46e566ee'
down_revision = '1e98da268fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_frps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vms_id', sa.String(length=100), nullable=False, comment='VMS ID'),
    sa.Column('internal_ip', sa.String(length=50), nullable=False, comment='内网 IP'),
    sa.Column('external_ip', sa.String(length=50), nullable=False, comment='公网 IP'),
    sa.Column('group_name', sa.String(length=100), nullable=True, comment='Group Name'),
    sa.Column('datacenter', sa.String(length=100), nullable=True, comment='机房位置'),
    sa.Column('isp_line', sa.String(length=100), nullable=True, comment='ISP 线路'),
    sa.Column('specific_line', sa.String(length=100), nullable=True, comment='线路详细信息'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_frpc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frpc_nickname', sa.String(length=100), nullable=True, comment='FRPC 昵称'),
    sa.Column('frpc_description', sa.Text(), nullable=True, comment='FRPC 说明'),
    sa.Column('frps_ports', sa.String(length=50), nullable=True, comment='FRPS 占用预留端口'),
    sa.Column('supplier', sa.String(length=100), nullable=True, comment='供应商'),
    sa.Column('supplier_delivery', sa.Text(), nullable=True, comment='供应商交付内容'),
    sa.Column('access_method', sa.String(length=50), nullable=True, comment='接入方式'),
    sa.Column('user', sa.String(length=100), nullable=True, comment='用房'),
    sa.Column('gost_address', sa.String(length=255), nullable=True, comment='Gost 地址'),
    sa.Column('actual_count', sa.Integer(), nullable=True, comment='实际数量'),
    sa.Column('health_check', sa.String(length=50), nullable=True, comment='健康检测方式'),
    sa.Column('remark_1', sa.Text(), nullable=True, comment='备注 1'),
    sa.Column('remark_2', sa.Text(), nullable=True, comment='备注 2'),
    sa.Column('frps_id', sa.Integer(), nullable=False, comment='FRPS ID'),
    sa.ForeignKeyConstraint(['frps_id'], ['table_frps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('proxies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('internal_ip', mysql.VARCHAR(length=50), nullable=False, comment='内网 IP 地址'),
    sa.Column('external_ip', mysql.VARCHAR(length=50), nullable=False, comment='公网 IP 地址'),
    sa.Column('group_name', mysql.VARCHAR(length=100), nullable=True, comment='分组名称'),
    sa.Column('datacenter', mysql.VARCHAR(length=100), nullable=True, comment='机房位置'),
    sa.Column('isp_line', mysql.VARCHAR(length=100), nullable=True, comment='ISP 线路信息'),
    sa.Column('specific_line', mysql.VARCHAR(length=100), nullable=True, comment='具体线路信息'),
    sa.Column('frpc_nickname', mysql.VARCHAR(length=100), nullable=True, comment='FRPC 昵称'),
    sa.Column('frpc_description', mysql.TEXT(), nullable=True, comment='FRPC 说明'),
    sa.Column('frps_ports', mysql.VARCHAR(length=50), nullable=True, comment='FRPS 占用或预留端口'),
    sa.Column('supplier', mysql.VARCHAR(length=100), nullable=True, comment='供应商名称'),
    sa.Column('supplier_delivery', mysql.TEXT(), nullable=True, comment='供应商交付内容'),
    sa.Column('access_method', mysql.VARCHAR(length=50), nullable=True, comment='接入方式（如 Squid、FRP）'),
    sa.Column('user', mysql.VARCHAR(length=100), nullable=True, comment='使用方'),
    sa.Column('gost_address', mysql.VARCHAR(length=255), nullable=True, comment='Gost 地址'),
    sa.Column('actual_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='实际数量'),
    sa.Column('health_check', mysql.VARCHAR(length=50), nullable=True, comment='健康检测方式'),
    sa.Column('remark_1', mysql.TEXT(), nullable=True, comment='备注 1'),
    sa.Column('remark_2', mysql.TEXT(), nullable=True, comment='备注 2'),
    sa.Column('remark_3', mysql.TEXT(), nullable=True, comment='备注 3'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('vms_id', mysql.VARCHAR(length=50), nullable=False, comment='机器 VMS 编号'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('table_frpc')
    op.drop_table('table_frps')
    # ### end Alembic commands ###
