"""empty message

Revision ID: 60736f3dcc3b
Revises: 7cf5ec21e011
Create Date: 2025-02-18 15:41:55.868629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60736f3dcc3b'
down_revision = '7cf5ec21e011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_frps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True, comment='FRPS备注'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_frps', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
