"""empty message

Revision ID: 7cf5ec21e011
Revises: 8310365b9c8a
Create Date: 2025-02-18 15:19:05.193971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf5ec21e011'
down_revision = '8310365b9c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='供应商名称'),
    sa.Column('contact', sa.String(length=100), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier_frps',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('frps_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frps_id'], ['table_frps.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'frps_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_frps')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
