"""empty message

Revision ID: 840702f3fdcd
Revises: 60736f3dcc3b
Create Date: 2025-02-19 09:36:57.885763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840702f3fdcd'
down_revision = '60736f3dcc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, comment='用户权限：admin 或 supplier'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
