"""empty message

Revision ID: 9840d06b9339
Revises: 00d2fe84db04
Create Date: 2024-12-10 14:36:18.201316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9840d06b9339'
down_revision = '00d2fe84db04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vms_id', sa.String(length=50), nullable=False, comment='机器 VMS 编号'))
        batch_op.drop_column('VMS')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proxies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('VMS', mysql.VARCHAR(length=50), nullable=False, comment='机器 VMS 编号'))
        batch_op.drop_column('vms_id')

    # ### end Alembic commands ###
