"""empty message

Revision ID: a0d31c19f8fe
Revises: 5e7f46e566ee
Create Date: 2024-12-14 18:41:28.347506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0d31c19f8fe'
down_revision = '5e7f46e566ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_frpc', schema=None) as batch_op:
        batch_op.alter_column('frps_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='FRPS ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_frpc', schema=None) as batch_op:
        batch_op.alter_column('frps_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='FRPS ID')

    # ### end Alembic commands ###
