"""empty message

Revision ID: c91fd6573d80
Revises: 
Create Date: 2025-02-25 16:52:48.866869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91fd6573d80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_frps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vms_id', sa.String(length=100), nullable=False, comment='VMS ID'),
    sa.Column('internal_ip', sa.String(length=50), nullable=False, comment='内网 IP'),
    sa.Column('external_ip', sa.String(length=50), nullable=False, comment='公网 IP'),
    sa.Column('group_name', sa.String(length=100), nullable=True, comment='Group Name'),
    sa.Column('datacenter', sa.String(length=100), nullable=True, comment='机房位置'),
    sa.Column('isp_line', sa.String(length=100), nullable=True, comment='ISP 线路'),
    sa.Column('specific_line', sa.String(length=100), nullable=True, comment='线路详细信息'),
    sa.Column('note', sa.Text(), nullable=True, comment='FRPS备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_frps',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('frps_id', sa.Integer(), nullable=False),
    sa.Column('service_port', sa.Integer(), nullable=False),
    sa.Column('port_range', sa.String(length=50), nullable=False),
    sa.Column('allocated_count', sa.Integer(), nullable=False),
    sa.Column('online_count', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['frps_id'], ['table_frps.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'frps_id')
    )
    op.create_table('table_frpc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frpc_nickname', sa.String(length=100), nullable=True, comment='FRPC 昵称'),
    sa.Column('frpc_description', sa.Text(), nullable=True, comment='FRPC 说明'),
    sa.Column('frps_ports', sa.String(length=50), nullable=True, comment='FRPS 占用预留端口'),
    sa.Column('supplier', sa.String(length=100), nullable=True, comment='供应商'),
    sa.Column('supplier_delivery', sa.Text(), nullable=True, comment='供应商交付内容'),
    sa.Column('access_method', sa.String(length=50), nullable=True, comment='接入方式'),
    sa.Column('user', sa.String(length=100), nullable=True, comment='使用方'),
    sa.Column('gost_address', sa.String(length=255), nullable=True, comment='Gost 地址'),
    sa.Column('actual_count', sa.Integer(), nullable=False, comment='实际数量'),
    sa.Column('health_check', sa.String(length=50), nullable=True, comment='健康检测方式'),
    sa.Column('remark_1', sa.Text(), nullable=True, comment='备注 1'),
    sa.Column('remark_2', sa.Text(), nullable=True, comment='备注 2'),
    sa.Column('frps_id', sa.Integer(), nullable=True, comment='FRPS ID'),
    sa.ForeignKeyConstraint(['frps_id'], ['table_frps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, comment='用户权限：admin 或 supplier'))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('role')

    op.drop_table('table_frpc')
    op.drop_table('supplier_frps')
    op.drop_table('table_frps')
    # ### end Alembic commands ###
