"""empty message

Revision ID: d36740e485ce
Revises: 034c8f145f17
Create Date: 2025-02-20 14:48:47.490491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36740e485ce'
down_revision = '034c8f145f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_frps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_port', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('port_range', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('allocated_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('online_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_frps', schema=None) as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('online_count')
        batch_op.drop_column('allocated_count')
        batch_op.drop_column('port_range')
        batch_op.drop_column('service_port')

    # ### end Alembic commands ###
