"""empty message

Revision ID: e247d19f983e
Revises: 6fcd5fb532d2
Create Date: 2024-12-24 13:41:27.064710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e247d19f983e'
down_revision = '6fcd5fb532d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scale_request')
    op.drop_table('scale_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scale_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=100), nullable=False, comment='FRPC 昵称'),
    sa.Column('progress', mysql.INTEGER(), autoincrement=False, nullable=False, comment='扩展量'),
    sa.Column('frps_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联 FRPS'),
    sa.Column('scale_request_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联扩容单'),
    sa.ForeignKeyConstraint(['frps_id'], ['table_frps.id'], name='scale_item_ibfk_1'),
    sa.ForeignKeyConstraint(['scale_request_id'], ['scale_request.id'], name='scale_item_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scale_request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=False, comment='主题'),
    sa.Column('description', mysql.TEXT(), nullable=False, comment='描述需求'),
    sa.Column('request_type', mysql.VARCHAR(length=50), nullable=False, comment='单据类型'),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False, comment='状态'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
